-- MIGRACIÓN: SOPORTE PARA QUIZZES EN SUBMISSIONS

ALTER TABLE public.submissions 
ADD COLUMN IF NOT EXISTS answers JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS auto_grade NUMERIC(4,2),
ADD COLUMN IF NOT EXISTS started_at BIGINT,
ADD COLUMN IF NOT EXISTS duration INTEGER,
ADD COLUMN IF NOT EXISTS is_auto_submitted BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'tarea';
