-- MIGRACIÓN: ENRIQUECIMIENTO DEL FORO
ALTER TABLE public.forum 
ADD COLUMN IF NOT EXISTS author_name TEXT,
ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'general',
ADD COLUMN IF NOT EXISTS likes JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS dislikes JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS read_by JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
